/**
 * @module canon-signal/cli/create
 *
 * Implements `npx canon-signal create` — generates a starter
 * `src/signal.ts` setup file in the user's project.
 *
 * Detects the user's framework from their `package.json` dependencies
 * (Hono, Express, Fastify, Next.js) and pulls the service name and
 * version from the same file. Outputs a TypeScript file with a typed
 * `AppAttributes` interface and a `createSignal<AppAttributes>()` call,
 * ready for the user to extend.
 *
 * Aborts if `src/signal.ts` already exists — never overwrites.
 */

import { writeFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

/**
 * Reads the consumer's `package.json` to extract name, version, and
 * dependencies. Returns an empty object on any error.
 */
function readPackageJson(cwd: string): { name?: string; version?: string; dependencies?: Record<string, string> } {
  try {
    return JSON.parse(readFileSync(resolve(cwd, 'package.json'), 'utf-8'))
  } catch {
    return {}
  }
}

/**
 * Detects which framework adapter to suggest based on the user's
 * installed dependencies. Checks in priority order: Hono → Express →
 * Fastify → Next.js. Defaults to Hono if none are detected.
 */
function detectFramework(deps: Record<string, string> = {}): string {
  if ('hono' in deps) return 'hono'
  if ('express' in deps) return 'express'
  if ('fastify' in deps) return 'fastify'
  if ('next' in deps) return 'next'
  return 'hono'
}

/**
 * Generates the contents of the `src/signal.ts` file as a string.
 *
 * The template includes:
 * - The required `import` statement from canon-signal
 * - A starter `AppAttributes` interface with placeholder comments
 *   showing common attribute patterns
 * - A `createSignal<AppAttributes>()` call with the user's service name
 *   and version
 * - A commented-out middleware registration line (Hono/Express/Next use
 *   `app.use(...)`, Fastify uses `app.register(...)`)
 */
type RuntimeTarget = 'node' | 'worker'

function generateNodeTemplate(serviceName: string, serviceVersion: string, framework: string): string {
  const middlewareComment = framework === 'fastify'
    ? "// app.register(signal.middleware({ framework: 'fastify' }))"
    : `// app.use('*', signal.middleware({ framework: '${framework}' }))`

  return `// src/signal.ts — Generated by canon-signal create
import { createSignal, type SignalAttributes } from 'canon-signal'

interface AppAttributes extends SignalAttributes {
  // Add your custom attributes here.
  // Non-optional properties are required on every root span.
  // Optional (?) properties can be set conditionally.
  //
  // Example:
  // 'app.user.id'?: string
  // 'app.customer.tier'?: 'free' | 'pro' | 'enterprise'
  // 'app.transaction.type'?: 'checkout' | 'refund'
}

export const signal = createSignal<AppAttributes>({
  service: {
    name: '${serviceName}',
    version: '${serviceVersion}',
    environment: process.env.NODE_ENV || 'development',
  },
  schema: { version: '1.0.0' },
})

// Add middleware to your app:
${middlewareComment}
`
}

function generateWorkerTemplate(serviceName: string, serviceVersion: string): string {
  return `// src/signal.ts — Generated by canon-signal create --runtime worker
import { createWorkerSignal, type SignalAttributes, type WorkerSignal } from 'canon-signal/worker'

export interface Env {
  NODE_ENV?: string
  OTEL_SERVICE_NAME?: string
  OTEL_RESOURCE_ATTRIBUTES?: string
  OTEL_EXPORTER_OTLP_ENDPOINT?: string
  OTEL_EXPORTER_OTLP_HEADERS?: string
  CANON_SIGNAL_SAMPLE_RATE?: string
  CANON_SIGNAL_DEBUG?: string
}

interface AppAttributes extends SignalAttributes {
  // Add your custom attributes here.
  // Non-optional properties are required on every root span.
  // Optional (?) properties can be set conditionally.
  //
  // Example:
  // 'app.user.id'?: string
  // 'app.customer.tier'?: 'free' | 'pro' | 'enterprise'
  // 'app.transaction.type'?: 'checkout' | 'refund'
}

let signal: WorkerSignal<AppAttributes> | undefined

export function getSignal(env: Env): WorkerSignal<AppAttributes> {
  signal ??= createWorkerSignal<AppAttributes>({
    env,
    service: {
      name: '${serviceName}',
      version: '${serviceVersion}',
      environment: env.NODE_ENV ?? 'production',
    },
    schema: { version: '1.0.0' },
    export: {
      traces: env.OTEL_EXPORTER_OTLP_ENDPOINT
        ? [{ type: 'otlp', endpoint: env.OTEL_EXPORTER_OTLP_ENDPOINT }]
        : [],
      logs: env.OTEL_EXPORTER_OTLP_ENDPOINT
        ? [{ type: 'otlp', endpoint: env.OTEL_EXPORTER_OTLP_ENDPOINT }]
        : [],
    },
  })
  return signal
}

// Add middleware to your Hono Worker app:
// app.use('*', (c, next) => getSignal(c.env).middleware()(c, next))
`
}

function normalizeRuntime(runtime: unknown): RuntimeTarget {
  return runtime === 'worker' ? 'worker' : 'node'
}

export interface CreateOptions {
  cwd?: string
  runtime?: unknown
}

/**
 * Runs the create command. Reads the user's `package.json`, detects the
 * framework, generates the template, and writes it to `src/signal.ts`.
 *
 * Aborts (calls `process.exit(1)`) if the target file already exists
 * — overwriting would silently destroy a customized setup file.
 *
 * @param cwd - Working directory (defaults to `process.cwd()`). Used as the base for `package.json` and the output path.
 */
export function runCreate(options: string | CreateOptions = process.cwd()): void {
  const cwd = typeof options === 'string' ? options : options.cwd ?? process.cwd()
  const runtime = normalizeRuntime(typeof options === 'string' ? undefined : options.runtime)
  const pkg = readPackageJson(cwd)
  const serviceName = pkg.name ?? 'my-service'
  const serviceVersion = pkg.version ?? '0.1.0'
  const framework = detectFramework({ ...pkg.dependencies })

  const outputPath = resolve(cwd, 'src', 'signal.ts')

  if (existsSync(outputPath)) {
    console.error(`canon-signal: ${outputPath} already exists. Aborting.`)
    process.exit(1)
  }

  const dir = dirname(outputPath)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }

  const content =
    runtime === 'worker'
      ? generateWorkerTemplate(serviceName, serviceVersion)
      : generateNodeTemplate(serviceName, serviceVersion, framework)
  writeFileSync(outputPath, content, 'utf-8')

  console.log(`Created ${outputPath}`)
  console.log()
  console.log('Next steps:')
  console.log('  1. Add your custom attributes to the AppAttributes interface')
  if (runtime === 'worker') {
    console.log('  2. Enable the Cloudflare nodejs_als or nodejs_compat compatibility flag')
    console.log("  3. Register middleware in your Hono Worker app: getSignal(c.env).middleware()")
  } else {
    console.log(`  2. Register middleware in your app: signal.middleware({ framework: '${framework}' })`)
    console.log('  3. Use signal.attr() in your handlers to enrich the root span')
  }
  console.log()
}
