/**
 * @module canon-signal/cli/install-docs
 *
 * Implements `npx canon-signal install-docs` — copies the agent
 * documentation suite from the package's `resources/` directory into
 * a `.canon-signal/` directory at the root of the user's repo.
 *
 * The intent is that AI agents working in the user's codebase can
 * read documentation locally without having to dig into `node_modules`.
 *
 * Behavior:
 * - Refuses to overwrite an existing `.canon-signal/` directory unless
 *   `--force` is passed.
 * - Copies every markdown file from the package's `resources/` directory
 *   into the user's `.canon-signal/`.
 * - Does NOT copy `resources/tutorial/` — that's handled by a separate
 *   command (`tutorial`) since the HTML file is for human consumption.
 * - Optionally creates an `AGENTS.md` at the repo root that points to
 *   the installed docs (for compatibility with the emerging convention
 *   of having `AGENTS.md` / `CLAUDE.md` files at the repo root).
 */

import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Resolves the path to the package's `resources/` directory at runtime.
 *
 * Two strategies:
 * 1. If we're running from a built distribution (`dist/cli/install-docs.js`),
 *    resources are at `<package-root>/resources/`. We walk up from `__dirname`
 *    until we find a `package.json` whose `name` is `canon-signal`.
 * 2. If we're running from source (during development), the same walk-up
 *    works because `src/cli/install-docs.ts` is also under the package root.
 *
 * Throws if the resources directory can't be located.
 */
function findResourcesDir(): string {
  // Get __dirname equivalent for ESM
  let currentDir: string
  try {
    currentDir = dirname(fileURLToPath(import.meta.url))
  } catch {
    // CJS fallback
    currentDir = __dirname
  }

  // Walk up looking for the canon-signal package root
  let dir = currentDir
  for (let i = 0; i < 10; i++) {
    const pkgJsonPath = join(dir, 'package.json')
    if (existsSync(pkgJsonPath)) {
      try {
        const pkg = JSON.parse(require('node:fs').readFileSync(pkgJsonPath, 'utf-8'))
        if (pkg.name === 'canon-signal') {
          const resourcesPath = join(dir, 'resources')
          if (existsSync(resourcesPath)) return resourcesPath
        }
      } catch {
        // ignore parse errors, keep walking
      }
    }
    const parent = dirname(dir)
    if (parent === dir) break
    dir = parent
  }

  throw new Error(
    'canon-signal: could not locate the resources/ directory. ' +
      'This usually means the package is corrupted or the resources/ folder ' +
      'is missing from the published package.',
  )
}

/**
 * Header prepended to every installed file. Records which canon-signal
 * version produced this copy so agents (and developers) can tell when
 * the docs are out of date relative to the installed package.
 */
function buildHeader(version: string, fileName: string): string {
  return `<!--
  This file was installed by \`npx canon-signal install-docs\` from canon-signal v${version}.
  Source: resources/${fileName}
  Do not edit this file directly — it will be overwritten on next install.
  Customize your usage by editing your project's signal.ts file instead.
-->

`
}

/**
 * Reads the version from canon-signal's own `package.json`.
 */
function readPackageVersion(resourcesDir: string): string {
  try {
    const pkgPath = resolve(resourcesDir, '..', 'package.json')
    const pkg = JSON.parse(require('node:fs').readFileSync(pkgPath, 'utf-8'))
    return pkg.version ?? '0.0.0'
  } catch {
    return '0.0.0'
  }
}

/**
 * Copies a single markdown file from the resources directory to the
 * destination, prepending a version header so consumers know what
 * canon-signal version produced it.
 */
function copyMarkdownFile(
  sourcePath: string,
  destPath: string,
  fileName: string,
  version: string,
): void {
  const content = require('node:fs').readFileSync(sourcePath, 'utf-8')
  const header = buildHeader(version, fileName)
  writeFileSync(destPath, header + content, 'utf-8')
}

/**
 * Generates a top-level AGENTS.md file at the repo root that points
 * agents into the installed docs.
 */
function buildAgentsMd(): string {
  return `# AGENTS.md

This project uses [\`canon-signal\`](https://github.com/anthropics/canon-signal) for observability. If you are an AI agent working in this codebase, read the documentation in \`.canon-signal/\` before writing or modifying instrumentation code.

## Where to start

1. **\`.canon-signal/CONSTITUTION.md\`** — The philosophical foundation. Trace-first observability, why the schema is a contract, when to use each signal type.
2. **\`.canon-signal/PLAYBOOK.md\`** — Explicit do's and don'ts. Read this before writing instrumentation code.
3. **\`.canon-signal/API.md\`** — Function-by-function reference for the \`signal.*\` API.
4. **\`.canon-signal/PATTERNS.md\`** — Working code examples for common scenarios.
5. **\`.canon-signal/ANTI_PATTERNS.md\`** — Things that look right but violate the principles.
6. **\`.canon-signal/TROUBLESHOOTING.md\`** — Common errors and fixes.

## The non-negotiables

- **Never use \`console.log\` in request handlers.** Use \`signal.attr()\`, \`signal.event()\`, or \`signal.log\` depending on the data shape.
- **Never bypass the \`AppAttributes\` schema.** New attributes must be added to the interface before they can be used.
- **Span names must be low-cardinality.** \`payment.process\` is valid; \`payment.process.\${userId}\` is not.
- **Always run tests after changing instrumentation.** The test harness catches drift.
- **Read the constitution before disagreeing with a design decision.** The reasoning is documented.

## Updating these docs

Run \`npx canon-signal install-docs --force\` to refresh the \`.canon-signal/\` directory with the version of the docs that matches your installed canon-signal package.
`
}

export interface InstallDocsOptions {
  cwd?: string
  force?: boolean
  /** When false, skip writing the root-level AGENTS.md file. Defaults to true. */
  writeAgentsMd?: boolean
}

/**
 * Runs the install-docs command.
 *
 * @param options.cwd - Working directory (default: `process.cwd()`).
 * @param options.force - Overwrite an existing `.canon-signal/` directory.
 * @param options.writeAgentsMd - Whether to also write a root-level `AGENTS.md`. Default: true.
 */
export function runInstallDocs(options: InstallDocsOptions = {}): void {
  const cwd = options.cwd ?? process.cwd()
  const force = options.force ?? false
  const writeAgentsMd = options.writeAgentsMd ?? true

  const resourcesDir = findResourcesDir()
  const version = readPackageVersion(resourcesDir)
  const destDir = resolve(cwd, '.canon-signal')

  // Check for existing destination
  if (existsSync(destDir) && !force) {
    console.error(
      `canon-signal: ${destDir} already exists. Pass --force to overwrite.`,
    )
    process.exit(1)
  }

  // Create the destination directory
  mkdirSync(destDir, { recursive: true })

  // Copy every top-level markdown file from resources/
  // (skip subdirectories like resources/tutorial/)
  const entries = readdirSync(resourcesDir)
  let copied = 0

  for (const entry of entries) {
    const sourcePath = join(resourcesDir, entry)
    const stats = statSync(sourcePath)

    if (stats.isDirectory()) continue
    if (!entry.endsWith('.md')) continue

    const destPath = join(destDir, entry)
    copyMarkdownFile(sourcePath, destPath, entry, version)
    copied++
  }

  // Optionally drop a root-level AGENTS.md
  if (writeAgentsMd) {
    const agentsMdPath = resolve(cwd, 'AGENTS.md')
    if (!existsSync(agentsMdPath) || force) {
      writeFileSync(agentsMdPath, buildAgentsMd(), 'utf-8')
    }
  }

  console.log(`Installed ${copied} canon-signal documentation file(s) to ${destDir}`)
  if (writeAgentsMd) {
    console.log(`Wrote AGENTS.md at ${cwd}`)
  }
  console.log()
  console.log('Next steps:')
  console.log('  1. Commit .canon-signal/ to your repo so agents can read it')
  console.log('  2. Re-run `npx canon-signal install-docs --force` after upgrading canon-signal')
  console.log()
}
